name: flutter_application_1
description: "Application scolaire Parent & Étudiant"
publish_to: 'none' # Ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  js: ^0.7.2

  # Gestion PDF et impression
  pdf: ^3.11.3
  printing: ^5.14.2

  # Gestion fichiers et images
  image: ^4.5.4
  image_picker: ^1.1.1
  image_picker_for_web: ^2.1.3
  file_picker: ^10.3.3
  http: ^1.5.0
  http_parser: ^4.1.2
  typed_data: ^1.4.0
  archive: ^4.0.7
  path_parsing: ^1.1.0
  qr: ^3.0.2
  crypto: ^3.0.6
  bidi: ^2.0.13
  barcode: ^2.2.9
  ffi: ^2.1.4
  petitparser: ^7.0.1
  xml: ^6.6.1

  # Flutter web / compatibilité
  web: ^1.1.1

  # ✅ Ajouts nécessaires pour les formulaires et la responsivité
  flutter_form_builder: ^9.2.1
  responsive_framework: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/avatar.jpg
    - assets/profile2.png
    - assets/folder.png
    - assets/doc.png
    - assets/Etudiants.png
    - assets/demande_documents.png
    - assets/historiques.png
    - assets/mes_documents.png
    - assets/profil_etudiant.png

