import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    email: v.string(),
    password: v.string(), // In a real app, store hashed passwords!
    firstName: v.optional(v.string()),
    lastName: v.optional(v.string()),
    dateOfBirth: v.optional(v.string()), // Date de naissance format YYYY-MM-DD (legacy)
    dateNaissance: v.optional(v.string()), // Date de naissance format YYYY-MM-DD (new)
    role: v.optional(v.string()),
    promotion: v.optional(v.string()),
    specialite: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    isOnline: v.optional(v.boolean()),
    photoUrl: v.optional(v.string()),
    phone: v.optional(v.string()),
    address: v.optional(v.string()),
    country: v.optional(v.string()),
    ville: v.optional(v.string()),
    profileComplete: v.optional(v.boolean()),
    stats: v.optional(v.object({
      totalDocuments: v.number(),
      processedDocuments: v.number(),
      rejectedDocuments: v.number(),
      pendingDocuments: v.number(),
      totalRequests: v.number(),
      processedRequests: v.number(),
      pendingRequests: v.number(),
    })),
    firstLogin: v.optional(v.boolean()),
    termsAcceptedVersion: v.optional(v.string()),
  }).index("by_email", ["email"]),
  documents: defineTable({
    name: v.string(),
    storageId: v.id("_storage"), // Reference to Convex storage
    url: v.string(), // Public URL of the file
    date: v.string(), // e.g., "13/08/2025"
    student: v.string(),
    year: v.string(), // e.g., "2025-2026"
    status: v.string(), // e.g., "Validé", "En cours", "Rejeté"
    statusType: v.string(), // e.g., "success", "pending", "rejected"
    docType: v.string(), // e.g., "Certificat", "Bulletin"
    condition: v.string(), // e.g., "Traité", "En cours"
    extension: v.string(), // e.g., "PDF"
    // Optional: reason for rejection
    reason: v.optional(v.string()),
  }),
  conventionRequests: defineTable({
    dateDebut: v.string(),
    dateFin: v.string(),
    stagiaireNom: v.string(),
    stagiairePrenom: v.string(),
    stagiaireCivilite: v.string(),
    stagiaireAdresse: v.string(),
    stagiaireCodePostal: v.string(),
    stagiaireVille: v.string(),
    stagiaireTelephone: v.string(),
    stagiaireEmail: v.string(),
    entrepriseType: v.string(),
    entrepriseNom: v.string(),
    entrepriseAdresse: v.string(),
    entrepriseCodePostal: v.string(),
    entrepriseVille: v.string(),
    entreprisePays: v.string(),
    entrepriseTelephone: v.string(),
    entrepriseFax: v.string(),
    entrepriseSiteWeb: v.string(),
    entrepriseNbEmployes: v.string(),
    representantNom: v.string(),
    representantPrenom: v.string(),
    representantCivilite: v.string(),
    representantFonction: v.string(),
    representantTelephone: v.string(),
    representantEmail: v.string(),
    taches: v.string(),
    environnementTechno: v.string(),
    formations: v.string(),
    objectifs: v.string(),
    nbCollaborateurs: v.string(),
    commentaires: v.string(),
    indemniteMontant: v.string(),
    indemniteMonnaie: v.string(),
    indemniteCommentaire: v.string(),
    userId: v.id("users"),
    userName: v.string(),
    userEmail: v.string(),
    requestType: v.string(),
    timestamp: v.string(),
    status: v.string(),
    createdAt: v.number(),
  }),
  attestations: defineTable({
    nom: v.string(),
    prenom: v.string(),
    dateNaissance: v.string(),
    promotion: v.string(),
    specialite: v.string(),
    anneeScolaire: v.string(),
    modalitePaiement: v.string(),
    fraisPreinscription: v.number(),
    fraisScolarite: v.number(),
    totalPaye: v.number(),
    modePaiement: v.string(),
    date: v.string(),
    userId: v.optional(v.id("users")),
    createdAt: v.number(),
    email: v.string(),
    userName: v.string(),
    requestType: v.string(),
    status: v.string(),
  }),
  actionLogs: defineTable({
    userId: v.id("users"),
    userEmail: v.string(),
    userName: v.optional(v.string()),
    action: v.string(),
    actionType: v.string(), // "login", "profile_update", "document_request", "document_delete", etc.
    details: v.optional(v.any()),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    timestamp: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_timestamp", ["timestamp"])
    .index("by_action_type", ["actionType"]),
  conventions: defineTable({
    // État civil du candidat
    civiliteCandidat: v.string(),
    nomCandidat: v.string(),
    prenomCandidat: v.string(),
    dateNaissanceCandidat: v.string(),
    lieuNaissanceCandidat: v.string(),
    paysCandidat: v.string(),
    nationaliteCandidat: v.string(),
    adresseCandidat: v.string(),
    villeCandidat: v.string(),
    codePostalCandidat: v.string(),
    telephoneCandidat: v.string(),
    portableCandidat: v.optional(v.string()),
    emailCandidat: v.string(),
    idCandidat: v.string(),
    photoCandidatStorageId: v.optional(v.id("_storage")),

    // Responsables légal
    civiliteRespLegal: v.string(),
    qualiteRespLegal: v.string(),
    nomRespLegal: v.string(),
    prenomRespLegal: v.string(),
    dateNaissanceRespLegal: v.string(),
    lieuNaissanceRespLegal: v.string(),
    paysRespLegal: v.string(),
    nationaliteRespLegal: v.string(),
    adresseRespLegal: v.string(),
    villeRespLegal: v.string(),
    codePostalRespLegal: v.string(),
    telephoneRespLegal: v.string(),
    portableRespLegal: v.optional(v.string()),
    emailRespLegal: v.string(),
    idRespLegal: v.string(),

    // Responsables financier
    civiliteRespFin: v.string(),
    qualiteRespFin: v.string(),
    nomRespFin: v.string(),
    prenomRespFin: v.string(),
    dateNaissanceRespFin: v.string(),
    lieuNaissanceRespFin: v.string(),
    paysRespFin: v.string(),
    nationaliteRespFin: v.string(),
    adresseRespFin: v.string(),
    villeRespFin: v.string(),
    codePostalRespFin: v.string(),
    telephoneRespFin: v.string(),
    emailRespFin: v.string(),
    idRespFin: v.string(),

    // Études antérieures
    etudes: v.array(v.object({
      annee: v.string(),
      etudeSuivie: v.string(),
      etablissement: v.string(),
      diplome: v.string(),
      dateObtention: v.string(),
    })),
    commentaire: v.optional(v.string()),
    createdAt: v.number(), // Add createdAt timestamp
  }),
  internshipConventions: defineTable({
    // Période
    dateDebut: v.string(),
    dateFin: v.string(),
    // Stagiaire
    stagiaireNom: v.string(),
    stagiairePrenom: v.string(),
    stagiaireCivilite: v.string(),
    stagiaireAdresse: v.string(),
    stagiaireCodePostal: v.string(),
    stagiaireVille: v.string(),
    stagiaireTelephone: v.string(),
    stagiaireEmail: v.string(),
    // Entreprise
    entrepriseType: v.optional(v.string()),
    entrepriseNom: v.string(),
    entrepriseAdresse: v.string(),
    entrepriseCodePostal: v.string(),
    entrepriseVille: v.string(),
    entreprisePays: v.optional(v.string()),
    entrepriseTelephone: v.optional(v.string()),
    entrepriseFax: v.optional(v.string()),
    entrepriseSiteWeb: v.optional(v.string()),
    entrepriseNbEmployes: v.optional(v.string()),
    // Représentant
    representantNom: v.string(),
    representantPrenom: v.string(),
    representantCivilite: v.string(),
    representantFonction: v.optional(v.string()),
    representantTelephone: v.optional(v.string()),
    representantEmail: v.optional(v.string()),
    // Descriptif
    taches: v.optional(v.string()),
    environnementTechno: v.optional(v.string()),
    formations: v.optional(v.string()),
    objectifs: v.optional(v.string()),
    nbCollaborateurs: v.optional(v.string()),
    commentaires: v.optional(v.string()),
    // Indemnité
    indemniteMontant: v.optional(v.string()),
    indemniteMonnaie: v.optional(v.string()),
    indemniteCommentaire: v.optional(v.string()),
    // Meta
    userId: v.id("users"),
    createdAt: v.number(),
  }),
  demandes: defineTable({
    type: v.string(), // "Bulletin de notes", "Attestation d'inscription", etc.
    userId: v.id("users"),
    submittedAt: v.number(),
    status: v.string(), // "En attente", "En cours", "Traitée", "Rejetée"
    attachmentId: v.optional(v.id("_storage")),
    title: v.optional(v.string()),
    // Informations utilisateur
    userEmail: v.optional(v.string()),
    userName: v.optional(v.string()),
    nom: v.optional(v.string()),
    prenom: v.optional(v.string()),
    dateNaissance: v.optional(v.string()),
    promotion: v.optional(v.string()),
    specialite: v.optional(v.string()),
    // Champs communs
    anneeScolaire: v.optional(v.string()),
    date: v.optional(v.string()),
    // Convention de stage
    entreprise: v.optional(v.string()),
    poste: v.optional(v.string()),
    adresseEntreprise: v.optional(v.string()),
    dateDebut: v.optional(v.string()),
    dateFin: v.optional(v.string()),
    duree: v.optional(v.string()),
    // Attestation de réussite
    moyenne: v.optional(v.string()),
    mention: v.optional(v.string()),
    // Autres champs dynamiques
    details: v.optional(v.any()),
    createdAt: v.optional(v.number()),
  }),
  alerts: defineTable({
    userId: v.id("users"),
    documentType: v.string(),
    deadline: v.string(),
    status: v.string(),
    actionStatus: v.string(),
    reminderDate: v.string(),
    email: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    promotion: v.string(),
    specialty: v.string(),
    profile: v.string(),
    isOnline: v.boolean(),
    createdAt: v.number(),
  }),
});